const dapps = [
  {
    name: "PancakeSwap",
    website: "https://pancakeswap.finance",
    description: "The most popular AMM on BSC! Earn CAKE through yield farming or win it in the Lottery, then stake it in Syrup Pools to earn more tokens! Initial Farm Offerings (new token launch model pioneered by PancakeSwap), NFTs, and more, on a platform you can trust.",
    logoURI: "https://raw.githubusercontent.com/pancakeswap/pancake-frontend/2ddaa21592f790bba52232c1f44c367b635f598f/public/images/cake.svg",
    multichain: false,
    hasToken: true,
    token: {
      name: "PancakeSwap Token",
      symbol: "CAKE",
      contractAddress: "0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82",
      decimal: 18,
      coingecko_id: "pancakeswap-token",
    },
    socials: {
      twitter: "https://twitter.com/PancakeSwap",
      telegram: "https://t.me/PancakeSwap",
      discord: "https://discord.gg/pancakeswap",
      github: "https://github.com/pancakeswap/",
      medium: "https://pancakeswap.medium.com/",
      youtube: "https://www.youtube.com/channel/UCYByrjvWt4WeBb40TWki-Yg",
    },
    chain: {
      name: "BNB Chain",
      symbol: "BSC",
      id: 51,
    },
    category: "DeFi, BSC, NFT, Exchange, Staking, Farming, Lottery",
  },
  {
    name: "BiSwap",
    website: "https://biswap.org/",
    description: "Biswap is the first DEX on Binance Smart Chain with a 3-type referral system and the lowest exchange fee 0.1% in the Defi space!",
    logoURI: "https://avatars.githubusercontent.com/u/82933564?s=200&v=4",
    multichain: false,
    hasToken: true,
    token: {
      name: "BiSwap Token",
      symbol: "BSW",
      contractAddress: "0x965F527D9159dCe6288a2219DB51fc6Eef120dD1",
      decimal: 18,
      coingecko_id: "biswap",
    },
    socials: {
      twitter: "https://twitter.com/Biswap_DEX",
      telegram: "https://t.me/biswap",
      discord: false,
      github: "https://github.com/biswap-org",
      medium: "https://biswap-dex.medium.com/",
      youtube: "https://www.youtube.com/channel/UCHartwkRUURf2Q7MlKOV84w",
    },
    chain: {
      name: "BNB Chain",
      symbol: "BSC",
      id: 51,
    },
    category: "DeFi, BSC, NFT, Exchange, Staking, Farming, Lottery, Refferal",
  },
  {
    name: "Venus Protocol",
    website: "https://www.venus.io/",
    description: "Earn, Borrow, & Lend on the #1 Decentralized Money Market on BNBChain",
    logoURI: "https://raw.githubusercontent.com/VenusProtocol/venus-protocol-interface/acf17a6b947123fcfd0925d5b1b7ff171884ef8b/public/coins/xvs.svg",
    multichain: false,
    hasToken: true,
    token: {
      name: "Venus",
      symbol: "XVS",
      contractAddress: "0xcf6bb5389c92bdda8a3747ddb454cb7a64626c63",
      decimal: 18,
      coingecko_id: "venus",
    },
    socials: {
      twitter: "https://www.venus.io/",
      telegram: "https://t.me/VenusProtocol",
      discord: "https://discord.com/invite/yjhVkzPSXE",
      github: "https://github.com/VenusProtocol/",
      medium: "https://medium.com/@Venus_protocol",
      youtube: false,
    },
    chain: {
      name: "BNB Chain",
      symbol: "BSC",
      id: 51,
    },
    category: "DeFi, BSC, Lending, Borrowing",
  },
];

export default dapps;
